/**
 * Client for the Python quant HTTP bridge (`mcp/quant_server/http_bridge.py`).
 *
 * The bridge publishes its tool manifest at `GET /tools`, derived by
 * introspection from the same functions the MCP server exposes. We turn that
 * manifest straight into AI SDK tools rather than re-declaring the schemas
 * here: a tool added in Python appears in the chat with no TypeScript change,
 * and the two surfaces cannot drift apart.
 *
 * Architecture principle (see repo README): AI orchestrates, Python
 * calculates. Nothing in this file computes a number.
 */

import { jsonSchema, tool, type ToolSet } from "ai";
import type { JSONSchema7 } from "@ai-sdk/provider";

export const BRIDGE_URL =
  process.env.QUANT_BRIDGE_URL ?? "http://127.0.0.1:8010";

/** Shape of one entry in the bridge's `/tools` manifest. */
export type ToolManifestEntry = {
  name: string;
  description: string;
  /** JSON Schema, generated by the bridge from the Python signature. */
  parameters: JSONSchema7;
};

export type BridgeStatus =
  | { ok: true; tools: number }
  | { ok: false; error: string };

/** Bridge reachability, for the sidebar indicator. */
export async function bridgeStatus(): Promise<BridgeStatus> {
  try {
    const res = await fetch(`${BRIDGE_URL}/health`, {
      cache: "no-store",
      signal: AbortSignal.timeout(3000),
    });
    if (!res.ok) return { ok: false, error: `bridge returned ${res.status}` };
    const body = (await res.json()) as { tools?: number };
    return { ok: true, tools: body.tools ?? 0 };
  } catch (err) {
    return {
      ok: false,
      error: err instanceof Error ? err.message : "unreachable",
    };
  }
}

export async function fetchManifest(): Promise<ToolManifestEntry[]> {
  const res = await fetch(`${BRIDGE_URL}/tools`, { cache: "no-store" });
  if (!res.ok) {
    throw new Error(
      `quant bridge /tools returned ${res.status}. Is it running on ${BRIDGE_URL}?`,
    );
  }
  const body = (await res.json()) as { tools: ToolManifestEntry[] };
  return body.tools;
}

/** Call one tool. Errors are RETURNED, never thrown — see `buildTools`. */
async function callTool(
  name: string,
  args: Record<string, unknown>,
): Promise<unknown> {
  let res: Response;
  try {
    res = await fetch(`${BRIDGE_URL}/tools/${name}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(args ?? {}),
      signal: AbortSignal.timeout(310_000),
    });
  } catch (err) {
    return {
      error: `Could not reach the quant engine at ${BRIDGE_URL}: ${
        err instanceof Error ? err.message : String(err)
      }. Start it with: uv run python -m mcp.quant_server.http_bridge`,
    };
  }

  const body = await res.json().catch(() => ({
    error: `quant bridge returned non-JSON (status ${res.status})`,
  }));

  // A 4xx from the bridge is usually the model's mistake (bad month, absent
  // parquet) and carries a message it can act on, so hand the message back as
  // a tool result instead of throwing. Throwing would abort the whole stream
  // and lose the chance to self-correct.
  if (!res.ok) {
    return {
      error:
        (body as { error?: string }).error ??
        `quant bridge error (status ${res.status})`,
    };
  }
  return (body as { result?: unknown }).result ?? body;
}

/**
 * Build the AI SDK tool set from the bridge manifest.
 *
 * `jsonSchema()` wraps the Python-derived schema without a zod re-declaration.
 */
export function buildTools(manifest: ToolManifestEntry[]): ToolSet {
  const tools: ToolSet = {};
  for (const entry of manifest) {
    tools[entry.name] = tool({
      description: entry.description,
      inputSchema: jsonSchema(entry.parameters),
      execute: async (args) =>
        callTool(entry.name, (args ?? {}) as Record<string, unknown>),
    });
  }
  return tools;
}

/**
 * Tools with side effects. The bridge withholds these from its manifest unless
 * QUANT_ALLOW_WRITE_TOOLS=1, so normally they never reach the model at all;
 * this list only drives the "confirm first" wording in the system prompt for
 * the case where an operator has deliberately enabled them.
 */
export const WRITE_TOOLS = ["download_month_data", "process_month_data"] as const;
